<?php
use Core\View\View;
?>

<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

    <title><?= View::yield('title') ?></title>
</head>
<body>

<div class="container" style="margin-top: 40px;">
    <div class="row">
        <div class="col-md-8">
            <?= View::yield('content') ?>
        </div>
        <div class="col-md-4">
            <h2>Боковая колонка</h2>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <span class="text-muted">Copyright &copy; 2021</span>
        </div>
    </div>
</div>
</body>
</html>